apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: default
type: Opaque
stringData:
  prometheus-additional.yaml: |
    - job_name: 'flask-app'
      metrics_path: /metrics
      static_configs:
        - targets: ['flask-service.default.svc.cluster.local:5000']